export { default as HomePage } from './Home/Home'
export { default as LoginPage } from './Auth/Login'
export { default as RegisterPage } from './Auth/Register'
export { default as VerificationPage } from './Auth/Verify'
export { default as MenuPage } from './Menu/Menu'
export { default as AllRestaurants } from './Restaurants/All'
